### ISSUE TITLE
Error loading channel 'StegaRef'

### ISSUE THREAD

**Issue by Vicor23** [epinna/weevely3#124]
I'm on Kali 2019.4 and I'm getting this error when trying to connect to some shells. Others work but you can only run some commands like 'ls' and 'cat'.

**Comment by epinna** [comment]
Does the prompt ends with "PHP>"?

**Comment by Vicor23** [comment]
No it does not. When I'm getting the Error loading channel 'StegaRef', the prompt is "weevely> " and for the ones that only some commands work it's the full path or doc root.

**Comment by epinna** [comment]
Try deleting (or renaming) the sessions folder `~/.weevely` and retry to connect.

**Comment by Vicor23** [comment]
I did that before and it's still the same. 
My version is 4.0.0. I have downloaded the 3.7.0 version and it's working without any issues. The issue on the v4 version must be related to the Python 3 port.

**Comment by epinna** [comment]
Well, still weird you see an error regarding `StegaRef` because that string is not in the code anymore.

However, I assume you generated that agent with an old version; you can try generating a new agent (by default it uses the most recent ObfPost agent/channel type), upload it, and try connect to the new one with the latest version you find here (do not use 4.0.0 that contains an error on the `cd` command).

**Comment by Vicor23** [comment]
Yes, the shells were generated with an older version. I'll keep using the 3.7.0, since there's no update on Kali, for the 4.0.0 version.
