### ISSUE TITLE
errors in requirements.txt?

### ISSUE THREAD

**Issue by sbrun** [epinna/weevely3#31]
Hello,
In the requirements .txt, I think there are wrong packages names
pyaml: should be replaced by PyYAML
dateutils: should be replaced by dateutil
It seems you import yaml and dateutil in your code (not pyaml and dateutils). 
Thanks

**Comment by epinna** [comment]
I don't see any error, that's are the package names in `pip`.

```
$ pip search pyaml
pyaml     - PyYAML-based module to produce pretty and readable YAML-serialized data
  INSTALLED: 15.5.7
  LATEST:    15.6.3
epinna$ pip search dateutils
dateutils              - Various utilities for working with date and datetime objects
  INSTALLED: 0.6.6 (latest)
```

**Comment by rhertzog** [comment]
@epinna Those packages do exist on Pypi but you are not using those packages. You are only using some of the dependencies of those packages.

Look more closely, the "dateutils" PyPi package provides a "dateutils" module which builds something on top of the "dateutil" module (provided by the "python-dateutil" PyPi package) so installing "dateutils" also install "python-dateutil"... but you are only using "python-dateutil" since you do "import dateutil".

And it's the same for the "pyaml" PyPi package, it provides a "pyaml" Python module that builds on top of the "yaml" Python module which is provided by the "PyYAML" PyPi package. And your code does "import yaml" so it only needs "PyYAML" and not "pyaml" in requirements.txt.

Please correct your dependencies to match what you are actually using. Thank you in advance.

**Comment by rhertzog** [comment]
For what it's worth, we discovered those issues while creating/updating the Debian package for Kali Linux. The dateutils/pyaml packages are not available in Kali and before adding them blindly, we checked what you were using and it turns out that they were not needed since you used the more popular (and already availabel) PyPi packages...

**Comment by epinna** [comment]
That's clear, really thanks for your advice. I'm going to fix it now.
