### ISSUE TITLE
[Errno 13] Permission denied: u'c:

### ISSUE THREAD

**Issue by buyyes** [epinna/weevely3#75]
When i try to use command ":audit_etcpasswd" i get this error:

[-][download] Error loading file 'c:\temp\tmp1mxiq1': [Errno 13] Permission denied: u'c:\\temp\\tmp1mxiq1'

I use cmd with administrative rights. What i`m doing wrong?

**Comment by epinna** [comment]
It is an error on creating temporary files on windows while executing the download functionality. I don't have a windows VM now to debug this but I'll keep this open for future fixes.

However since Windows is not properly supported, I suggest on the meanwhile to run Weevely on a Linux virtual machine.
