### ISSUE TITLE
HTTPS Proxy support ?

### ISSUE THREAD

**Issue by HarishHary** [epinna/weevely3#86]
Would be nice to have a HTTPS proxy ?

**Comment by epinna** [comment]
Yes it would :) Not sure if I have time to develop it, but I'm keeping this open in case anyone would work on this.

**Comment by ixiss78** [comment]
Hi !
Could have been asked more nicely for an open-sourced project :)

I think you should look into the proxy.py file @HarishHary , I guess it should be just a few lines to add, did not have to look into it yet but should be doing it pretty soon.

Good luck !

**Comment by HarishHary** [comment]
Well, I tried actually. Seems like it's more than that. We have to change the 'curl.py' file too, since @epinna reimplemented a curl-like system to make it work. I wonder why ? I don't have time right now to look into it. But yeah ! I will try. Thank you for your advice @ixiss78 !

**Comment by ixiss78** [comment]
It seemed like it for me too, but I'll be looking into it with a friend in a few days when we'll have a bit more time to work on it !
We can try to update this thread if we are successful !

**Comment by epinna** [comment]
Hello guys,

@HarishHary - I implemented `:net_proxy` module using a curl-like system because I wanted to keep the HTTP proxy traffic incapsulated within the weevely protocol. 

Writing a standard, dumb proxy that accepts CONNECT verb and forward opaque TLS traffic is not doable with the single-request-single-response protocol used by weevely.

I see two possible solutions: 

1. Develop a proxy module that terminates the TLS connection to the local i.e. :8080 port and forward the single requests and responses, like Burp Suite does. This is probably doable but kind of complex.
2. Develop a proxy module that just forwards the TLS-encrypted traffic, like [reGeorg](https://github.com/sensepost/reGeorg) does. This won't be encapsulated and obfuscated within weevely traffic, but it's still acceptable.

I don't currently have time to work on this, but your pull requests are always welcome :)

**Comment by epinna** [comment]
The `:net_proxy` module you can find in the `ssl-proxy` branch now supports HTTPS.

There is still some problem on the generated certificate chain so you can't just add the CA certificate to your browser and just browse freely, but you have to add the SSL certificate for every new HTTP website you visit (quite annoying). 

I still have some work to fix this before merging to the `master` branch, but feel free to try it considering it's under heavy development.

**Comment by epinna** [comment]
Guys `:net_proxy` now supports HTTPS connections, see here

https://github.com/epinna/weevely3/wiki/Proxy-HTTP-and-HTTPS-traffic

Far from being perfect, seems acceptable from most of the sites, even complex portals. Give it a try if you can. I'll work on some adjustments before the next release though.
